### PR TITLE
Fix wrong processing of ApplicationIdentification

### LINKED ISSUE #218: Photon does not allow a list of ApplicationIdentification elements that the composition conforms
ST2067-2-2016 section 6.1 allows a list of ApplicationIdentification elements to which a composition conforms. So for example, it is perfectly valid for a composition that conforms to application type 2 to indicate that it also conforms to application type 2e.

I.E: <cc:ApplicationIdentification>http://www.smpte-ra.org/schemas/2067-20/2016 http://www.smpte-ra.org/schemas/2067-21/2016</cc:ApplicationIdentification>

Instead of treating this a a list of strings, the code treats this as a single string and thus is unable to locate the application type in the list of valid applications.

### PR DESCRIPTION
**Pull request by cconcolato**
Closes #218

Per 2067-2 (2013 or 2016), the ApplicationIdentification element in the CPL can contain multiple URIs. Current code assumes it's a single string.

This PR fixes that using a Set and validating that a CPL conforms to all the applications in the Set. Previous public methods that used a single String are kept for backwards compatibility for now but marked as deprecated.

### CODE REVIEW

File: src/main/java/com/netflix/imflibrary/st2067_2/IMFCompositionPlaylistType.java [hunk 1]
```diff
@@ -66,7 +66,24 @@
     private final List<IMFEssenceDescriptorBaseType> essenceDescriptorList;
     private final IMFErrorLogger imfErrorLogger;
     private final String coreConstraintsVersion;
-    private final String applicationId;
+    private final Set<String> applicationIdSet;
+
+
+    @Deprecated
```
Comment (davidt-netflix) [inline src/main/java/com/netflix/imflibrary/st2067_2/IMFCompositionPlaylistType.java]: Add Javadoc explaining why the old method was deprecated, and what new signature should be used instead.
https://docs.oracle.com/javase/tutorial/java/annotations/predefined.html

File: src/main/java/com/netflix/imflibrary/st2067_2/IMFCompositionPlaylistType.java [hunk 2]
```diff
@@ -440,8 +457,21 @@ public String getCoreConstraintsVersion() {
      *
      * @return a string representing ApplicationIdentification for this CompositionPlaylist
      */
+    @Deprecated
     public String getApplicationIdentification() {
-        return this.applicationId;
+        if (this.applicationIdSet.size() > 0) {
+            return this.applicationIdSet.iterator().next();
+        } else {
+            return null;
```
Comment (davidt-netflix) [inline src/main/java/com/netflix/imflibrary/st2067_2/IMFCompositionPlaylistType.java]: The old applicationId was being initialized as an empty string, rather than a null.
The change for compatibility should maybe use `return "";` instead.

File: src/main/java/com/netflix/imflibrary/st2067_2/ApplicationCompositionFactory.java [hunk 3]
```diff
@@ -101,22 +101,30 @@ public static ApplicationComposition getApplicationComposition(ResourceByteRange
...
+                    if (applicationCompositionType == null) {
+                        clazz = Application2ExtendedComposition.class;
+                        imfErrorLogger.addError(IMFErrorLogger.IMFErrors.ErrorCodes.IMF_CPL_ERROR, IMFErrorLogger.IMFErrors.ErrorLevels.NON_FATAL,
+                                String.format("Unsupported/Missing ApplicationIdentification %s in CPL", applicationIdentification));
+                    } else {
+                        clazz = applicationCompositionType.getClazz();
+                    }
+
+                    Constructor<?> constructor = clazz.getConstructor(IMFCompositionPlaylistType.class, Set.class);
+                    composition = (ApplicationComposition) constructor.newInstance(imfCompositionPlaylistType, homogeneitySelectionSet);
```
Comment (davidt-netflix) [inline src/main/java/com/netflix/imflibrary/st2067_2/ApplicationCompositionFactory.java]: Isn't `composition` being overwritten each time if there is more than one _ApplicationIdentification_? That also mean that the order that AppId are provided matters, since only the last composition is returned.

I'm not familiar with the use of multiple ApplicationIdentifications, but is the intent to still return a single composition that conforms to ALL of them? Or a map of compositions, one for each AppId?

File: src/main/java/com/netflix/imflibrary/st2067_2/IMFCompositionPlaylistType.java (hunk 2 above)
Comment (cconcolato) [reply src/main/java/com/netflix/imflibrary/st2067_2/IMFCompositionPlaylistType.java]: Good catch. Will fix.

File: src/main/java/com/netflix/imflibrary/st2067_2/ApplicationCompositionFactory.java (hunk 3 above)
Comment (cconcolato) [reply src/main/java/com/netflix/imflibrary/st2067_2/ApplicationCompositionFactory.java]: You're right that the composition would be overwritten and therefore that the returned object would be dependent on the order of applications declared. In the current approach, the getter actually does a validation of the CPL, so the idea is that it does a validation against all declared applications, even if it returns only the last one. This is not ideal, but in practice, all CPLs we have seen so far declare a single applications. So the result will be identical. In the future, we could introduce a different getter to force which application is returned.
